name: my_cookbook
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  mdc_web: ^0.4.1+1

dev_dependencies:
  sass_builder: ^2.0.0
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
